! Generated by c68 4.5 27 Feb 99 (Sep  1 2022) from "ram.i"
	.sect	.text
	.sect	.rom
	.sect	.data
	.sect	.bss
	.sect	.text
	.align	2
	.extern _test
_test:
	bra	I_1
I_2:
	move.w	163886,-2(a6)
	move.l	#0,d3
	bra	I_4
I_3:
	pea	4096
	move.l	8(a6),-(a7)
	jsr	_bzero
	add.w	#8,a7
I_6:
	add.l	#1,d3
I_4:
	cmp.l	#1000,d3
	bcs	I_3
I_5:
	clr.l	d0
	move.w	163886,d0
	clr.l	d1
	move.w	-2(a6),d1
	sub.l	d1,d0
I_7:
	move.l	-14(a6),d3
	unlk	a6
	rts
I_1:
	link	a6,#-10
	move.l	d3,-(a7)
	bra	I_2
I_16:
	.ascii	"%d"
	.data1	0x9
	.ascii	"%d"
	.data1	0x9
	.ascii	"%c %d"
	.data1	0xa,0x0
I_15:
	.ascii	"global var"
	.data1	0x9
	.ascii	"%d"
	.data1	0x9
	.ascii	"%c %d"
	.data1	0xa,0x0
I_14:
	.ascii	"static var"
	.data1	0x9
	.ascii	"%d"
	.data1	0x9
	.ascii	"%c %d"
	.data1	0xa,0x0
I_13:
	.ascii	"local var"
	.data1	0x9
	.ascii	"%d"
	.data1	0x9
	.ascii	"%c %d"
	.data1	0xa,0x0
I_12:
	.ascii	"main function at %d"
	.data1	0xa,0x0
I_11:
	.ascii	"test function at %d"
	.data1	0xa,0x0
I_10:
	.ascii	"w"
	.data1	0x0
I_9:
	.ascii	"flp1_ram_out"
	.data1	0x0
	.align	2
	.extern _main
_main:
	bra	I_17
I_18:
	lea	_test,a2
	move.l	#262144,d6
	move.l	#72,d7
	lea	_fprintf,a3
	lea	_printf,a4
	pea	I_10
	pea	I_9
	jsr	_fopen
	move.l	d0,d3
	add.w	#8,a7
	move.l	a2,-(a7)
	pea	I_11
	jsr	(a4)
	add.w	#8,a7
	move.l	a2,-(a7)
	pea	I_11
	move.l	d3,-(a7)
	jsr	(a3)
	lea	12(a7),a7
	pea	_main
	pea	I_12
	jsr	(a4)
	add.w	#8,a7
	pea	_main
	pea	I_12
	move.l	d3,-(a7)
	jsr	(a3)
	lea	12(a7),a7
	pea	-4100(a6)
	jsr	(a2)
	move.l	d0,(a7)
	lea	-4100(a6),a0
	cmp.l	a0,d6
	bhi	I_19
	move.l	d7,d0
	bra	I_20
I_19:
	move.l	#76,d0
I_20:
	move.l	d0,-(a7)
	pea	-4100(a6)
	pea	I_13
	jsr	(a4)
	lea	16(a7),a7
	pea	-4100(a6)
	jsr	(a2)
	move.l	d0,(a7)
	lea	-4100(a6),a0
	cmp.l	a0,d6
	bhi	I_21
	move.l	d7,d0
	bra	I_22
I_21:
	move.l	#76,d0
I_22:
	move.l	d0,-(a7)
	pea	-4100(a6)
	pea	I_13
	move.l	d3,-(a7)
	jsr	(a3)
	lea	20(a7),a7
	pea	I_8
	jsr	(a2)
	move.l	d0,(a7)
	cmp.l	#I_8,d6
	bhi	I_23
	move.l	d7,d0
	bra	I_24
I_23:
	move.l	#76,d0
I_24:
	move.l	d0,-(a7)
	pea	I_8
	pea	I_14
	jsr	(a4)
	lea	16(a7),a7
	pea	I_8
	jsr	(a2)
	move.l	d0,(a7)
	cmp.l	#I_8,d6
	bhi	I_25
	move.l	d7,d0
	bra	I_26
I_25:
	move.l	#76,d0
I_26:
	move.l	d0,-(a7)
	pea	I_8
	pea	I_14
	move.l	d3,-(a7)
	jsr	(a3)
	lea	20(a7),a7
	pea	_d
	jsr	(a2)
	move.l	d0,(a7)
	cmp.l	#_d,d6
	bhi	I_27
	move.l	d7,d0
	bra	I_28
I_27:
	move.l	#76,d0
I_28:
	move.l	d0,-(a7)
	pea	_d
	pea	I_15
	move.l	d3,-(a7)
	jsr	(a3)
	move.l	#0,d5
	bra	I_30
I_29:
	pea	4096
	jsr	_malloc
	move.l	d0,d4
	add.w	#4,a7
	beq	I_31
I_33:
	move.l	d4,-(a7)
	jsr	(a2)
	move.l	d0,-4108(a6)
	move.l	-4108(a6),(a7)
	cmp.l	d6,d4
	bcs	I_34
	move.l	d7,d0
	bra	I_35
I_34:
	move.l	#76,d0
I_35:
	move.l	d0,-(a7)
	move.l	d4,-(a7)
	move.l	d5,-(a7)
	pea	I_16
	jsr	(a4)
	lea	20(a7),a7
	move.l	-4108(a6),-(a7)
	cmp.l	d6,d4
	bcs	I_36
	move.l	d7,d0
	bra	I_37
I_36:
	move.l	#76,d0
I_37:
	move.l	d0,-(a7)
	move.l	d4,-(a7)
	move.l	d5,-(a7)
	pea	I_16
	move.l	d3,-(a7)
	jsr	(a3)
	lea	24(a7),a7
I_32:
	add.l	#1,d5
I_30:
	cmp.l	#1024,d5
	bcs	I_29
I_31:
	lea	20(a7),a7
	move.l	d3,-(a7)
	jsr	_fclose
	movem.l	-4144(a6),d3/d4/d5/d6/d7/a2/a3/a4
	unlk	a6
	rts
I_17:
	link	a6,#-4112
	movem.l	d3/d4/d5/d6/d7/a2/a3/a4,-(a7)
	bra	I_18
	.sect	.bss
I_8:
	.space	4096
	.extern _d
_d:
	.space	4096
	.sect	.text
